import "./assets/styles/globals.scss"
import GlobalNav from "./components/Nav"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="main-layout-wrapper">
          <GlobalNav />
          {children}
        </div>
      </body>
    </html>
  )
}
